export const AIRLINE_OPTIONS = [
  'Emirates',
  'Qatar Airways',
  'Singapore Airlines',
  'Delta Air Lines',
  'United Airlines',
  'American Airlines',
  'British Airways',
  'Lufthansa',
  'Air France',
  'Turkish Airlines',
  'Etihad Airways',
  'Cathay Pacific',
  'ANA (All Nippon Airways)',
  'Japan Airlines',
  'KLM',
  'Swiss International Air Lines',
  'Virgin Atlantic',
  'Air Canada',
  'Korean Air',
  'IndiGo',
  'Air India',
  'Vistara',
  'Ryanair',
  'EasyJet',
  'Flydubai',
  'Alaska Airlines',
  'JetBlue',
  'Southwest Airlines',
  'Qantas',
  'Air New Zealand'
];

export const HOTEL_OPTIONS = [
  'Marriott International',
  'Hilton Worldwide',
  'Hyatt Hotels Corporation',
  'IHG Hotels & Resorts',
  'AccorHotels',
  'Wyndham Hotels & Resorts',
  'Choice Hotels International',
  'Best Western Hotels',
  'Four Seasons Hotels',
  'The Ritz-Carlton',
  'Sheraton',
  'Westin',
  'Holiday Inn',
  'Radisson Hotel Group',
  'MGM Resorts',
  'Fairmont Hotels & Resorts',
  'Shangri-La Hotels and Resorts',
  'Mandarin Oriental',
  'Rosewood Hotels & Resorts',
  'InterContinental'
];

export const CAR_RENTAL_OPTIONS = [
  'Hertz',
  'Avis',
  'Enterprise Rent-A-Car',
  'Budget Rent a Car',
  'Sixt',
  'National Car Rental',
  'Alamo Rent a Car',
  'Thrifty Car Rental',
  'Dollar Rent A Car',
  'Europcar',
  'Localiza',
  'Goldcar',
  'Hertz 24/7',
  'Zipcar'
];

export const CRUISE_OPTIONS = [
  'Royal Caribbean International',
  'Carnival Cruise Line',
  'Norwegian Cruise Line',
  'MSC Cruises',
  'Princess Cruises',
  'Celebrity Cruises',
  'Holland America Line',
  'Disney Cruise Line',
  'Virgin Voyages',
  'Cunard Line',
  'Costa Cruises',
  'P&O Cruises',
  'AIDA Cruises',
  'Viking Ocean Cruises',
  'Azamara',
  'SilverSea Cruises',
  'Regent Seven Seas Cruises'
];
